name: Concurrent Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: nginx:latest
    
    strategy:
      matrix:
        build_number: [1, 2, 3, 4, 5, 6]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          echo "Hello world ${{ matrix.build_number }}"
          # Add your build and test commands here
